### ISSUE TITLE
RND seems to be broken

### ISSUE THREAD

**Issue by schauder** [inexorabletash/jsbasic#10]
RND(40) seems to result in a random number in the interval [0, 1), but according to my AppleII Basic Programming Manual should return a random number in the interval [0, 39]

**Comment by inexorabletash** [comment]
Can you cite the exact text of the programming manual?

**Comment by inexorabletash** [comment]
Check out ftp://ftp.apple.asimov.net/pub/apple_II/documentation/programming/basic/Applesoft%20BASIC%20Programming%20Reference%20Manual%20-%20Apple%20Computer.pdf page 102:

> RND (aexpr)
> Returns a random real number greater than or equal to 0 and less than 1.
>
> If \aexpr\ is greater than zero, RND(aexpr) generates a new random number each time it is used.
>
> If \aexpr\ is less than zero, RND(aexpr) generates the same random number each time it is used with the same \aexpr\, as if from a permanent random number table built into the APPLE. If a particular _negative_ argument is used to generate a random number, then subsequent random numbers generated with _positive_ arguments will follow the same sequence each time. A different random sequence is initialized by each different negative argument. The primary reason for using a negative argument for RND is to initialize (or "seed") a _repeatable_ sequence of random numbers. This is particularly helpful in debugging programs that use RND.
>
> If \aexpr\ is zero, RND(aexpr) returns the most recent previous random number generated (CLEAR and NEW do not affect this. Sometimes this is easier than assigning the last random number to a variable in order to save it.

**Comment by inexorabletash** [comment]
It's possible you're thinking of Integer BASIC, which was used on the Apple II and Apple II+. There, `RND(n)` returns an integer value from [0 ,n). This project is an Applesoft BASIC environment, which was the default on the Apple IIe, IIc and IIgs.

Integer BASIC manual: http://www.classiccmp.org/cini/pdf/Apple/Apple%20II%20Basic%20Programming%20Manual.pdf

...which, of course, doesn't call it "Integer BASIC" as there wasn't the need for a distinguishing prefix.

**Comment by schauder** [comment]
Looks like you are right. I'm using exactly the manual you linked to and I used it back in the days when I learned programming. So I guess I was using Integer BASIC although I thought I used the floating point version. 

Thanks for clarifying, and thanks for the project. I have tons of fun showing my kids how I learned to program with your project.
