### ISSUE TITLE
Error isn't raised

### ISSUE THREAD

**Issue by naumanumer** [inexorabletash/jsbasic#14]
When i execute following code is must raise `For with out Next`

```
10 for a = 1 to 10
20 print a
```

But the output is:
```
1
```

**Comment by inexorabletash** [comment]
That's a perfectly valid program. A `NEXT` is never required. That's the expected output. Try it on a real Apple II or an actual emulator.

**Comment by inexorabletash** [comment]
![screen shot 2016-12-05 at 8 09 33 am](https://cloud.githubusercontent.com/assets/771547/20892234/3420b0e0-bac2-11e6-8266-df2f62748b63.png)

**Comment by inexorabletash** [comment]
I should note that this is true of Applesoft BASIC. It may not be true of other variants - I never used GW-BASIC for example. Good luck with your fork!

**Comment by naumanumer** [comment]
This is a great project but I have two problems with:
* basic.js is too long i want to split it into files
* I need more advanced console. The structure is really well expect rendering text from img.

I want it to be used with my electron.js app. So i will try to write it using angular.js and node.js.
