### ISSUE TITLE
Documentation of init method

### ISSUE THREAD

**Issue by cfjedimaster** [inexorabletash/jsbasic#17]
Can you provide some more information about how init should be run? I'm trying to build a sever-side version that would *not* support inputs or graphics of any kind, just basic (heh) sequential execution and then returning the output as a string. Possible?

**Comment by inexorabletash** [comment]
Cool project! I'm happy to answer questions (or review refactors/fixes as necessary to support it)

You'll want to look at [script.js](https://github.com/inexorabletash/jsbasic/blob/master/script.js#L104) for an example; it's more minimal than the full UI of the site, although still more complex than you'll need. It should be something like:

```js
const program = basic.compile(source);
program.init({ ... }); // complexity here
while (program.step() !== basic.STATE_STOPPED) continue;
```
So as you asked, the complexity is in what to pass for `init()`. The only thing that should be required is `tty` which would be an object implementing parts of what's in `tty.js`.

You can probably get away with something like this:

```js
  program.init({
    tty: {
      getCursorPosition: function() { return { x: 0, y: 0 }; },
      setCursorPosition: function() { },
      getScreenSize: function() { return { width: 80, height: 24 }; },
      writeChar: function(ch) { host.console.putc(ch.replace(/\r/g, '\n')); },
      writeString: function(string) { host.console.puts(string.replace(/\r/g, '\n')); },
      readChar: function(callback) {
        callback(host.console.getc());
      },
      readLine: function(callback, prompt) {
        host.console.puts(prompt);
        callback(host.console.gets().replace(/[\r\n]*/, ''));
      }
    });
```
...where you'll need to replace all of the `host.console` calls with whatever you want to capture output and simulate input (e.g. always calling back with the empty string)

Let me know if you need more help.

**Comment by cfjedimaster** [comment]
This is working well - thank you so much. To be clear, this is just for a dumb demo I'm going to build for OpenWhisk (openwhisk.apache.org), so it's fun, not crucial. :)

**Comment by cfjedimaster** [comment]
One more question - and this should maybe be a new bug - let me know. 

I'm seeing that if I run 2 calls that the basic object is not clearing the old code. 

So I do `program = basic.compile('10 print "ray"')` and I get the right output, but if I then do: `program = basic.compile('10 print "ray2"')`, the output is ray/ray2. 

Any idea why?

**Comment by cfjedimaster** [comment]
Sorry - dumb error - ignore. :)

**Comment by inexorabletash** [comment]
Feel free to ask any further questions, but closing this for now.

**Comment by cfjedimaster** [comment]
Thank you again for the help - this is the blog post it led to: https://www.raymondcamden.com/2017/08/01/serverless-basic/
