### ISSUE TITLE
RND function doesn't seed on clock

### ISSUE THREAD

**Issue by baskaufs** [inexorabletash/jsbasic#24]
For fun I was resurrecting a [program I wrote in 1983](https://github.com/baskaufs/msc/blob/master/historical/code.bas) that generated a random code.  I used RND(1) to have the computer generate a random number.  However, the same seed seems to be used every time the program is restarted, so my game always generates the same code for a given chosen number of characters and positions.  

I don't specifically remember how this worked on the Apple ][ but typically, the random number generators used the clock as the seed so that the same sequence wouldn't be generated every time the program was run.  In some cases (I think DEC BASIC), we had to include a RANDOMIZE statement prior to using the RND function.  But I don't think Applesoft BASIC had that.  

Is there any way to get a seed from the clock to avoid this issue?

By the way, this is super fun and cool!

**Comment by inexorabletash** [comment]
The original Apple did not have a clock. Instead, you'd manually seed the PRNG using a timer that was incremented while waiting for user input, at `PEEK(78)` and `PEEK(79)`. This is "emulated" by making those use the browser's PRNG. So you can do, for example:

```basic
10 R = PEEK(78) + 256*PEEK(79) : R = RND(-R) : REM Seed with random data
```
