### ISSUE TITLE
Power (^) Operator should be right associative

### ISSUE THREAD

**Issue by yiransheng** [inexorabletash/jsbasic#25]
Example program:

```
10 LET X = 4^2^-1
20 PRINT X
```
Should be interpreted as `LET X = 4^(2^-1)`, thus printing: `2`

Currently this is handled as `LET X = (4^2)^-1`, resulting in `1/16 =0.0625`

Not sure about how official Apple Basic handles it, but in javaScript for example, `4**2**-1` evaluates to `2` in right associative order.

Parsing code should handle this differently than other binary operators:
https://github.com/inexorabletash/jsbasic/blob/0ad3bcf56afd4ead6556eb15b108d14faf15e7d6/basic.js#L1574

A simple (self) recursive fix would be:
```javaScript
function parsePowerExpression() {
	var lhs = parseUnaryExpression(), rhs;
	if (test('operator', '^', true)) {
		rhs = parsePowerExpression(); // <-- self recursion here

		enforce_type(lhs.type, 'number');
		enforce_type(rhs.type, 'number');

		return { source: 'Math.pow(' + lhs.source + ',' + rhs.source + ')', type: 'number' };
	}
	return lhs;
}
```

**Comment by inexorabletash** [comment]
Via the Apple II emulator "Virtual ][", which uses the real Apple ROMs:

![image](https://user-images.githubusercontent.com/771547/50619307-559d1600-0ead-11e9-91be-c4c638451b5d.png)

Looks like it's acting as expected.

There's also a test for precedence, which presumably I wrote and compared against a real machine (and/or actual emulator): https://github.com/inexorabletash/jsbasic/blob/master/samples/sample.unittests.txt#L847
