### ISSUE TITLE
Support for peek/poke in lowmem

### ISSUE THREAD

**Issue by bferguson3** [inexorabletash/jsbasic#27]
Hello!

I love the work you've done so far, it's probably the best tool I've found for coding quickly in BASIC for the A][. The only thing I think is missing is being able to poke/peek the empty 3rd page of memory ($0300-$03cf) for use with custom user variables. Would this be extremely difficult to add? If it's not in the pipeline then I could take a look myself.

Thanks!

**Comment by inexorabletash** [comment]
What would you do with bytes stored in memory locations like $300 given that assembly routines are not supported? It seems like a strange way to store data.

**Comment by bferguson3** [comment]
I was under the impression bitwise operations were supported in Apple basic
but they and and or operations are clearly different than the assembly
counterparts. That being the case this is unnecessary, but thanks for the
response.

2019年2月23日(土) 16:19 Joshua Bell <notifications@github.com>:

**Comment by inexorabletash** [comment]
Okay - thanks for clarifying. 

It's possible to add, and at least would offer a simple floor-and-clamp to 256 operation, but without a use case I worry that it would let users assume they can poke in routines to call.
