### ISSUE TITLE
"Select a sample..." not working

### ISSUE THREAD

**Issue by nerun** [inexorabletash/jsbasic#37]
Hey, what a great script!

Just one issue: i have downloaded to my PC, then click index.html, and it opens at browser. it works except for "Select a sample..." dropdown menu. It loads nothing. And the default sample ("Hello World") doesn't appear by default. The right white screen is blank.

Except for this issue, this Applesoft BASIC emulator works really great!

**Comment by Nerun** [comment]
Addendum: the URL https://inexorabletash.github.io/jsbasic/ works fine! This issue just happens when download to my PC.

**Comment by inexorabletash** [comment]
You need to run a local web server. The behavior of web pages loaded from local files over `file:` URLs is basically unspecified and mostly broken. Whatever browser you're using would appear to prevent XMLHttpRequest to local resources, which is how the files are loaded.
