### ISSUE TITLE
Variables are not distinguished if first two characters of variable name are same. 

### ISSUE THREAD

**Issue by zetwhite** [inexorabletash/jsbasic#38]
```basic
10 AAB = 10
20 AAC = 20 
30 PRINT (AAB)
```
* expected result : 10 
* result in https://calormen.com/jsbasic/ : 20 

Since 10 is  assigned to AAB, 10 must be printed. 
But when i tried this code in https://inexorabletash.github.io/jsbasic/ , 20 is printed. 

Anyway, Thank you for your great code. 
It was fun playing with it!

**Comment by inexorabletash** [comment]
AppleSoft only pays attention to the first two characters of the variable name, so this is intentional and working as intended. Try it out on a real Apple or an actual emulator like www.scullinsteel.com/apple2/e
