### ISSUE TITLE
Dead links in index.html

### ISSUE THREAD

**Issue by mobluse** [inexorabletash/jsbasic#43]
- _Apple2JS_ has a dead link http://www.megidish.net/apple2js/, but https://www.megidish.net/apple2js/index.html works.
- _Logo in Javascript_ has a relative link that is not working when you fork the JSBASIC site or move it: ../jslogo; it could be changed to https://inexorabletash.github.io/jslogo/.

**Comment by inexorabletash** [comment]
thanks!
