### ISSUE TITLE
Add easy way to change screen resolution (enhancement)

### ISSUE THREAD

**Issue by nerun** [inexorabletash/jsbasic#46]
Could you add an easy way to change screen resolution? Screens seems to be 560 x 384 px. Could you add an option to manual resize or setup another size according to the user's screen size?

2 screens of 560px are ok, it is 1120px wide, but for a Full HD screen (1920 x 1080) maybe 840 x 576 px would be good (it's 1.5 times larger).

**Comment by inexorabletash** [comment]
What's wrong with using browser zoom? If you zoom in Chrome (View > Zoom In) the setting will be persisted for that site.

**Comment by nerun** [comment]
Ok ok
