### ISSUE TITLE
Backspace and Delete don't work in INPUT

### ISSUE THREAD

**Issue by mobluse** [inexorabletash/jsbasic#47]
If you press Backspace or Delete it adds a character and doesn't remove a character from the buffer. Test e.g. with this program:
```
10 INPUT "ENTER:";A$:A=VAL(A$)
20 PRINT A$,A
30 GOTO 10
```
E.g. type QW55[BS][BS][BS][BS]66[CR]
This was supposed to enter 66, but QW55____66 is entered. Delete gives the same result. This might be compatible with other emulators. Left arrow works more as expected, but leaves text on screen.
ENTER:QW55####66

Ctrl+H works as Left arrow. I understand Apple II didn't have Backspace or Delete, but at least Backspace should work as Ctrl+H i.e. Left arrow, I think.

**Comment by inexorabletash** [comment]
That's how the Apple II worked. Applesoft BASIC was written for the Apple II Plus, which didn't have Backspace/Delete. When the Apple IIe was introduced with the Delete key, the INPUT routine was not updated to incorporate support for Delete, so it enters a literal Delete character (U+007F). 

When you hit Left Arrow it backs up within the input buffer but (as you note) doesn't clear the display. You can compare against https://apple2ts.com/ and https://www.scullinsteel.com/apple2/e - and those are proper emulators.

**Comment by mobluse** [comment]
"Apple IIe was introduced with the Delete key", but not with the Backspace key, I presume. Then there is no reason AFAIK why Backspace couldn't send Ctrl+H.
